[package]
name = "Division"
version = "0.1.0"
authors = ["Yoonsung <lvev9925@naver.com>"]

[dependencies.iron]
version = "*"

[dependencies.bodyparser]
version = "*"

[dependencies]
rustc-serialize = "*"